"""Forensic report export.

`GET /scans/{scan_id}/report` renders the full case file (verdict,
header chain, origin + geo intel, attribution, indicators, custody
block) with an integrity footer. `export=true` appends a
report-export row to the hash chain and writes an audit entry.
"""

import hashlib
import json
from datetime import datetime

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session

from app.api.intel import _hops_payload
from app.config import get_settings
from app.dependencies import get_current_user, get_db, owned_or_404
from app.engines.intel.origin import build_origin_trace
from app.models.campaign import Campaign
from app.models.evidence import EvidenceChain
from app.models.email import Email
from app.models.indicator import Indicator
from app.models.scan import Scan, Verdict
from app.services.evidence_service import append_evidence, audit
from app.services.ip_intel_service import IpIntelService
from app.services.pii import maybe_mask_email, maybe_mask_ip
from app.models.user import User

router = APIRouter()

_DISCLAIMER = (
    "This report was generated by an automated analysis system for "
    "defensive security and evidentiary purposes. Scores are "
    "probabilistic indicators, not proof of malicious intent. Verify "
    "critical conclusions against primary evidence (the retained raw "
    "message and its integrity hashes) before acting."
)


def _canonical_sha256(payload: dict) -> str:
    blob = json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str)
    return hashlib.sha256(blob.encode("utf-8")).hexdigest()


@router.get("/scans/{scan_id}/report")
async def scan_report(
    scan_id: int,
    export: bool = Query(False, description="Append evidence-chain row + audit"),
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user),
):
    scan = db.get(Scan, scan_id)
    owned_or_404(scan, user)
    email = db.get(Email, scan.email_id)
    owned_or_404(email, user)
    verdict = db.query(Verdict).filter(Verdict.scan_id == scan.id).first()

    # ── gather evidence ────────────────────────────────────────
    breakdown = (verdict.breakdown if verdict else None) or {}
    hops = _hops_payload(db, email)
    origin = build_origin_trace(
        [
            {
                "from_ip": h["from_ip"],
                "from_host": h["from_host"],
                "helo": h["helo"],
                "by_host": h["by_host"],
                "timestamp_utc": h["timestamp"],
                "is_internal": h["is_internal"],
            }
            for h in hops
        ]
    )
    intel_row = None
    if origin is not None:
        intel_row = IpIntelService(db).cached_only(origin.ip)

    indicators = (
        db.query(Indicator)
        .filter(Indicator.scan_id == scan.id)
        .order_by(Indicator.type, Indicator.value)
        .all()
    )
    campaign = None
    if scan.campaign_id:
        campaign = db.get(Campaign, scan.campaign_id)
    evidence_rows = (
        db.query(EvidenceChain)
        .filter(
            EvidenceChain.scan_id == scan.id,
            EvidenceChain.user_id == user.id,
        )
        .order_by(EvidenceChain.id.asc())
        .all()
    )

    settings = get_settings()

    # ── assemble (PII-masked when enabled) ─────────────────────
    report = {
        "scan": {
            "id": scan.id,
            "status": scan.status,
            "started_at": scan.started_at.isoformat() if scan.started_at else None,
            "completed_at": (
                scan.completed_at.isoformat() if scan.completed_at else None
            ),
        },
        "email": {
            "message_id": email.message_id,
            "sender": maybe_mask_email(email.sender),
            "to": maybe_mask_email(email.to_address),
            "subject": email.subject,
            "date": email.date,
            "fetched_at": (
                email.fetched_at.isoformat() if email.fetched_at else None
            ),
        },
        "verdict": (
            {
                "final_score": verdict.final_score,
                "classification": verdict.classification,
                "scores": {
                    "ai": verdict.ai_score,
                    "url": verdict.url_score,
                    "attachment": verdict.attachment_score,
                    "header": verdict.header_score,
                },
                "ai_label": verdict.ai_label,
                "flags": breakdown.get("ai", {}).get("flags", []),
                "bec": breakdown.get("ai", {}).get("bec"),
                "lookalike": breakdown.get("ai", {}).get("lookalike"),
                "created_at": (
                    verdict.created_at.isoformat() if verdict.created_at else None
                ),
            }
            if verdict
            else None
        ),
        "header_forensics": breakdown.get("header"),
        "attribution": breakdown.get("attribution"),
        "origin": (
            {
                **(origin.to_dict() if origin else {}),
                "ip": maybe_mask_ip(origin.ip) if origin else None,
                "intel": intel_row.to_dict() if intel_row else None,
            }
            if origin
            else None
        ),
        "received_chain": hops,
        "indicators": [i.to_dict() for i in indicators],
        "campaign": campaign.to_dict() if campaign else None,
        "evidence_chain": [e.to_dict() for e in evidence_rows],
    }

    report_sha = _canonical_sha256(report)
    integrity = {
        "report_sha256": report_sha,
        "generated_at": datetime.utcnow().isoformat(),
        "app_version": settings.APP_VERSION,
        "disclaimer": _DISCLAIMER,
    }

    if export:
        source = email.source
        append_evidence(
            db,
            email_id=email.id,
            scan_id=scan.id,
            raw_sha256=source.raw_sha256 if source else None,
            report_sha256=report_sha,
            actor="report-export",
            user_id=user.id,
        )
        audit(
            db,
            "report_export",
            actor=user.email,
            entity_type="scan",
            entity_id=scan.id,
            detail={"report_sha256": report_sha},
            user_id=user.id,
        )
        # refresh custody block so the response shows the new row
        report["evidence_chain"] = [
            e.to_dict()
            for e in db.query(EvidenceChain)
            .filter(
                EvidenceChain.scan_id == scan.id,
                EvidenceChain.user_id == user.id,
            )
            .order_by(EvidenceChain.id.asc())
            .all()
        ]

    return {"report": report, "integrity": integrity}
